### ISSUE TITLE
Retry Policy does not work if TimeotException is thrown

### ISSUE THREAD

**Issue by DmytroBevziuk** [nikolic-bojan/soap-client#2]
Hi there,
I am trying to use WCF and HttpClient Retry policy like this:
```c#
services.AddHttpClient("TestClient")
    .AddPolicyHandler(Policy.HandleResult<HttpResponseMessage>(r => !r.IsSuccessStatusCode)
            .Or<Exception>()
            .RetryAsync(5, (ex, count) =>
            {
                Console.WriteLine("Retry count: " + count);
            })
    );
``` 

But the retry does not work if the timeout exception is thrown.
I set up the timeout like mentioned in the example:

```c#
client.Endpoint.Binding.CloseTimeout = TimeSpan.FromMilliseconds(10);
client.Endpoint.Binding.OpenTimeout = TimeSpan.FromMilliseconds(10);
client.Endpoint.Binding.ReceiveTimeout = TimeSpan.FromMilliseconds(10);
client.Endpoint.Binding.SendTimeout = TimeSpan.FromMilliseconds(10);
``` 

Retry works if, for example, EndpointNotFoundException is thrown, but not for Timeout.

**Comment by DmytroBevziuk** [comment]
@nikolic-bojan looks like I have gaps in usage of AddPolicyHandler and it should not work as I described. Could you, please, delete the issue because it does not make sense.
Thank you.

**Comment by nikolic-bojan** [comment]
Hi @DmytroBevziuk,
Just took a look at the issue. Will close it for now and try to remove it.
This code base is 3+ years old, so there might be some issues with it and new versions of packages or .NET.
Hope you will resolve your issue fast.

BR, Bojan
